### ISSUE TITLE
First seen trends

### ISSUE THREAD

**Issue by afergadis** [afergadis/twitter-bursting-topics-n-fake-news#2]
First seen trends are bursting?

If they are, what is the "bursting" percent of them?

**Comment by kzama** [comment]
We can assume that are "bursting" . We can have a default percentage for them (ex. 100%) or a default value (NAN/-1) which denotes that are bursting but appeared for the first time (in order to display them to the user either way and without taking into account the percentage that he/she specified).

**Comment by afergadis** [comment]
First seen trends takes zero as burstiness value and a flag `fistSeen` is set to true.
